name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install

  deploy:

    runs-on: ubuntu-latest
    needs: build

    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B clean install
    - name: Bundle
      run: mvn -B -f imagey-server/pom.xml meecrowave:bundle
    - name: Copy bundle
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.KEY }}
        source: imagey-server/target/imagey-server-meecrowave-distribution.zip
        target: ~/
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mv ~/imagey-server/target/imagey-server-meecrowave-distribution.zip ~/
          ~/imagey-server-distribution/bin/meecrowave.sh stop
          unzip -o ~/imagey-server-meecrowave-distribution.zip
          export SMTP_HOST=${{ vars.SMTP_HOST }}
          export SMTP_PORT=${{ vars.SMTP_PORT }}
          export SMTP_USER=${{ vars.SMTP_USER }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          ~/imagey-server-distribution/bin/meecrowave.sh start
